ДЗ 1
BrashMack/2024-2-VK-EDU-Frontend-G-Vostrikov pull request #1
Opened 2024-09-24 20:54 UTC by BrashMack

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

2024-09-26 15:49 UTC, Ivan-Bir requested changes

2024-09-26 15:49 UTC, Ivan-Bir commented on .gitignore
> +node_modules/
Привет! Добро пожаловать на курс
Я буду твоим ментором и буду рад ответить на любые вопросы по курсу

2024-09-26 15:49 UTC, Ivan-Bir commented on README.md:Zone.Identifier
> +[ZoneTransfer]
Непонятный файл

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (typeof (bytes) != 'number' || bytes < 0 || !Number.isInteger(bytes)) return false;
1) Почти всегда правильным будет использование строго равенства или неравенства (===, !==) вместо нестрогого
2) Не совсем верно обрабатываешь входные данные. По условию возможны float, потому они тоже относятся к числам, а ты их отсеиваешь
3) Даже если тело условия из одной строки, то обычно его оборачивают в блок {}

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +    const measure = ['B', 'KB', 'MB', 'GB', 'TB'];
Петабайт тоже возможен сегодня

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  else {
else в данном случае избыточен, если выполняется условие, то происходит выход из функции

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +        return `${Number.isInteger(bytes) ? bytes : bytes.toFixed(2).replace(/0+$/, '')} ${measure[i]}`
Лайк, что знаешь регулярки, но давай тут не городить работу с форматированием.
Для чисел можно использовать стандартную parseFloat

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +        return `${Number.isInteger(bytes) ? bytes : bytes.toFixed(2).replace(/0+$/, '')} ${measure[i]}`
Не очень хороший паттерн делать return из цикла со счетчиком

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +// другая группа проверок
Откуда взялся этот коммент))?

2024-09-26 15:49 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Начинают обычно с позитивных кейсов. Так чуть проще воспринимать код теста сверху вниз

2024-09-26 15:49 UTC, Ivan-Bir commented on correctSentence.js
> +  // your solution goes here
Лишний комент

2024-09-26 15:49 UTC, Ivan-Bir commented on correctSentence.js
> +  return `${text.charAt(0).toUpperCase()}${text.slice(1)}${text[text.length - 1] == '.' ? '' : '.'}`;
1) Нет проверки входных данных. Посмотри что будет в пограничных кейсах. Тест тоже не будет лишним
2) В одну строку сложно воспринимать, мы не экономим строчки исходного кода, поэтому давай разнесём

2024-09-26 15:49 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  const non_uniq = data.filter((element, index, array) => array.indexOf(element) !== index);
Получилось неоптимально. В худшем случае, сложность этого алгоритма n^2, потому что метод поиска индекса всё также перебирает массив. То есть в худшем случае (все элементы уникальны), на каждую итерацию цикла будет происходить весь обход массива. Давай попробуем уложиться в фиксированное число обходов массива

2024-09-26 15:49 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return data.filter(element => non_uniq.includes(element));
Даже если у стрелочной функции один параметр, то его принято оборачивать в скобки

2024-09-26 15:49 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Тесты не покрывают граничные случаи. Давай поправим

2024-09-26 22:04 UTC, BrashMack commented on convertBytesToHuman.js
> +  if (typeof (bytes) != 'number' || bytes < 0 || !Number.isInteger(bytes)) return false;
2. Просто по смыслу самой функции мы получаем на вход количество байт, а байты не могут быть не целыми.

2024-09-26 22:05 UTC, BrashMack commented on convertBytesToHuman.js
> +  if (typeof (bytes) != 'number' || bytes < 0 || !Number.isInteger(bytes)) return false;
Просто по смыслу самой функции мы получаем на вход количество байт, а байты не могут быть не целыми.

2024-09-26 22:05 UTC, BrashMack commented on convertBytesToHuman.js
> +  if (typeof (bytes) != 'number' || bytes < 0 || !Number.isInteger(bytes)) return false;
2. Просто по смыслу самой функции мы получаем на вход количество байт, а байты не могут быть не целыми.

2024-09-26 22:05 UTC, BrashMack commented on convertBytesToHuman.js
> +  if (typeof (bytes) != 'number' || bytes < 0 || !Number.isInteger(bytes)) return false;
2. Просто по смыслу самой функции мы получаем на вход количество байт, а байты не могут быть не целыми.

2024-09-26 22:08 UTC, BrashMack commented on convertBytesToHuman.test.js
> +// другая группа проверок
На лекции мы импортировали эти функции и тесты из готовой библиотеки, так что там уже были какие то заготовки и комментарии, которые я не убрал)

2024-09-26 22:11 UTC, BrashMack commented on correctSentence.js
> +  return `${text.charAt(0).toUpperCase()}${text.slice(1)}${text[text.length - 1] == '.' ? '' : '.'}`;
Нас просили написать тест только для "convertBytesToHuman.js", так как для остальных двух функций тесты уже были, поэтому не менял их. Доработаю.

2024-09-27 12:40 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (typeof (bytes) != 'number' || bytes < 0 || !Number.isInteger(bytes)) return false;
Всё правильно, работаем только с целыми байтами
Но возвращать в этом случае false я считаю слишком жестко

2024-09-27 12:41 UTC, Ivan-Bir commented on correctSentence.js
> +  return `${text.charAt(0).toUpperCase()}${text.slice(1)}${text[text.length - 1] == '.' ? '' : '.'}`;
Приучаемся, что если видим, что можем что-то улучшить на месте, то улучшаем. Если не заметил предыдущий разработчик, то можешь ты

2024-09-27 12:43 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  else {
Если что-то правишь как сказано в замечании, то закрывай тред. Открытыми оставляй для дискуссии

2024-09-28 09:48 UTC, Ivan-Bir approved these changes
Есть небольшие моменты на поправить (на твоё усмотрение), апрув ставлю

2024-09-28 09:48 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Посмотри что будет если передать NaN
Для справки: typeof NaN === 'number'

2024-09-28 09:48 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  for (i = 0; i < 6; ++i) {
1) Не обратил сначала внимание - не используем магические константы в коде. Что мешает написать measure.length ?
2) Для чего потребовалось выносить переменную счетчика из под for?

2024-09-28 09:48 UTC, Ivan-Bir commented on correctSentence.js
> +  if (typeof (text) !== 'string') return "It's not a string!"
Даже для однострочных ифаков принято использовать { }

2024-09-28 09:48 UTC, Ivan-Bir commented on correctSentence.js
> +  if (text === '' || !/[a-zA-Z]/.test(text[0])) return "Bad string!"
Не очень хороший паттерн из функции, которая возвращает строку возвращать ошибку в том же типе. Достаточно просто вернуть пустую строку или null, чтобы в вызывающем коде писать что-то типа
if (!correctSentence(text)) {
return;
}

2024-09-28 09:48 UTC, Ivan-Bir commented on correctSentence.test.js
> +})
Не забываем добавлять пустую строку в конец файла

2024-09-29 13:47 UTC, martinkomitsky approved these changes
12!

2024-09-29 13:47 UTC, merged

2024-09-30 21:28 UTC, BrashMack commented on convertBytesToHuman.js
> +  for (i = 0; i < 6; ++i) {
2. Переменную счетчика вынес из цикла, чтобы делать return вне цикла. Так как было замечание, что делать return в счётном цикле - плохая практика.

2024-09-30 21:38 UTC, BrashMack commented on correctSentence.test.js
> +})
А это зачем?)