ДЗ 2
BrashMack/2024-2-VK-EDU-Frontend-G-Vostrikov pull request #2
Opened 2024-10-07 15:26 UTC by BrashMack

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

Что было сделано:
* Сверстал сайт по предоставленному макету, выполнил все пункты ДЗ.
* К сожалению и скрипт и стили остались в index.html, хотел вынести их, но постоянно происходила ошибка:
Refused to execute script from 'http://localhost:8080/index.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
С CSS модулем то же самое.
Читал что либо путь не верный, либо сервер настроен криво. Путь точно верный, а что там не так с конфигом webpack я не знаю и не разбираюсь в этом(
Поэтому всё в одном файле, не было времени разбираться с этим.

2024-10-10 09:09 UTC, Ivan-Bir commented
Привет! Добавь ссылочку на деплой

2024-10-10 12:04 UTC, BrashMack commented
> Привет! Добавь ссылочку на деплой

https://brashmack.github.io/2024-2-VK-EDU-Frontend-G-Vostrikov/

2024-10-10 14:11 UTC, Ivan-Bir requested changes
Продукт выглядит стильно и приятно, отправка с клавиатуры работает. Продолжай в том же духе!

Маленький момент тут, что неработающие кнопки вообще лучше скрыть, чтобы меньше было ощущения, что продукт сырой. Лучше меньше фич, но работающих на ура
Ничего супер критичного по коду не заметил, но из-за немалого количества замечаний апрув поставлю после правок.

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +body {
На тег не хорошо накидывать стили. Этим обычно пользуются в очень ограниченных задачах, например для сброса стандартных стилей, накладываемых например браузером. Для твоей задачи можно использовать отдельный контейнер, и там задать стили

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +.chat-header img {
Стараемся избегать сложных селекторов. Почти в 100% случаев можно обойтись отдельным классом с понятным именем. Здесь и далее (везде, к сожалению)

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.html
> +            </div>
Такое уносят в js в какое-нибудь отдельное место, типа mocks.js, используя те же методы, что будут использоваться для рантайма. В html надо задать только структуру (хотя и это тоже можно спокойно унести под js-компонент, оставив в html только подгрузку скрипта приложения. В этом дз пока ок)

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    form.dispatchEvent(new Event('submit'));
Искусственно выбрасывать события не самый правильный способ. Что мешает сразу вызвать код обработчика?

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +});
Давай унесем весь иницилизирующий код под функу

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    chatBody.scrollTop = chatBody.scrollHeight;
Классно, что это есть

2024-10-10 14:11 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +        addMessage(messageText, true);
Неоптимально по ресурсам. На каждое добавление ты конвертишь в json все сообщения. Если сообщений будет много, то это будет сказываться на производительности. 
Предлагаю придумать другой способ хранения сообщений

2024-10-10 14:38 UTC, Ivan-Bir commented
Насчет пустых строк и prettier. Нужно покопаться в его настройках
https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code-ru

2024-10-11 00:31 UTC, BrashMack commented
> Продукт выглядит стильно и приятно, отправка с клавиатуры работает. Продолжай в том же духе!
> 
> Маленький момент тут, что неработающие кнопки вообще лучше скрыть, чтобы меньше было ощущения, что продукт сырой. Лучше меньше фич, но работающих на ура Ничего супер критичного по коду не заметил, но из-за немалого количества замечаний апрув поставлю после правок.

Нерабочие кнопки убрал, только скрепку оставил, очень уж она вписывается туда)

2024-10-12 16:03 UTC, Ivan-Bir approved these changes
Незначительные замечания. Исправить можно их в следующем дз. Также добавить новых продуктовых фич

2024-10-12 16:03 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +.chat-header .avatar {
Сложный селектор прекрасно заменяется на класс chat-header-avatar. Так проще дебажить + мы не завязываемся на структуру html, которая может впоследствии измениться, что повлечет баги

2024-10-12 16:03 UTC, Ivan-Bir commented on simple-chat/src/index.html
> +            <!-- <i class="material-symbols-outlined back toucheble" title="Назад">arrow_back_ios_new</i> -->
Коменты убрать

2024-10-12 16:03 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +loadMessages();
Советую почитать и использовать событие жизненного цикла страницы
https://learn.javascript.ru/onload-ondomcontentloaded

2024-10-13 17:32 UTC, HaseProgram approved these changes
Отлично, 10!

2024-10-13 17:33 UTC, merged