ДЗ 3
BrashMack/2024-2-VK-EDU-Frontend-G-Vostrikov pull request #3
Opened 2024-10-17 20:56 UTC by BrashMack

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

Что было сделано:
* Список чатов
* Переход из списка в конкретный чат и обратно
* Чаты загружаются из localStorage
*  Выполнены все условия задания, но планируются доработки :)

2024-10-21 14:40 UTC, Ivan-Bir requested changes
Есть существенные моменты в коде, надо поправить

По UI обозначу eщё пару моментов
1) Когда поднимается модалка обычно делают так, её можно было закрыть нажатием на внешнюю область и не нажать лишнего в остальном интерфейсе
2) Расположение кнопок в форме тоже можно поменять. Обычно слева снизу как раз кнопка подтверждения (подпись добавить тоже не будет лишним), а крестик или справа сверху, или вообще скрыт
3) Просить URL-картинки совсем не юзер френдли. Конечно хотелось бы видеть картинку, загруженную с устройства
4) Дергается менюшка в бургер-меню при наведении курсором

2024-10-21 14:40 UTC, Ivan-Bir commented on simple-chat/src/chatlist.css
> +.popup-menu .option {
Копирую из предыдущего дз (не игнорим). "Стараемся избегать сложных селекторов. Почти в 100% случаев можно обойтись отдельным классом с понятным именем. Здесь и далее (везде, к сожалению)"

2024-10-21 14:40 UTC, Ivan-Bir commented on simple-chat/src/chatlist.html
> +<!DOCTYPE html>
Этого не должно быть. Мы учимся делать SPA, поэтому должен остаться только index.html, а экраны уносим в компоненты, и из js рендерим. Это позволит обойтись без перезагрузки страницы и ускорит отображение

2024-10-21 14:40 UTC, Ivan-Bir commented on simple-chat/src/chatlist.js
> +        }
1. Пора расширять до возможности хранения данных других чатов. Сейчас это выглядит как один большой костыль
2. Алерты - это зло в чистом виде. Его вызов - синхронное действие, которое блокирует весь интерфейс, пока не закроешь. Правильно выводить ошибку на форме

2024-10-21 14:40 UTC, Ivan-Bir commented on simple-chat/src/chatlist.js
> +        chatList?.appendChild(chatElement);
Если объединить в одну операцию, то отрисовка выполнится быстрее и будет меньше дерганий. Здесь и везде.
Обрати внимание на https://developer.mozilla.org/ru/docs/Web/API/Document/createDocumentFragment

2024-10-21 14:40 UTC, Ivan-Bir commented on simple-chat/src/index.html
> +                <i class="material-symbols-outlined toucheble icons" title="Дополнительно">more_vert</i>
Как уже говорил в предыдущем дз, мы не оставляем кнопки ради кнопок. Приложение должно быть _работающим_ на каждом этапе своего развития

2024-10-21 14:41 UTC, Ivan-Bir commented on simple-chat/src/chatlist.html
> +<!DOCTYPE html>
Как раз проблема из описания PR решится, если перейти на рендеринг экранов из js

2024-10-27 11:05 UTC, Ivan-Bir commented
Почти ничего исправлено с предыдущего ревью(
Исправить открытые замечания в следующем дз
+ Ещё 2 момента по UI:
1) Предусмотреть дефолтную картинку
2) Макс ширину модалки лучше задавать фиксированную. На широком монике расплывается сильно. Дизайн кнопки сабмита советую поменять. При остальном красивом интерфейсе она выглядит прямиком из 2000-х

Апрув только по формальным требованиям

2024-10-27 11:05 UTC, Ivan-Bir approved these changes

2024-10-27 17:46 UTC, merged

2024-10-27 17:46 UTC, martinkomitsky commented
7

2024-10-27 18:03 UTC, BrashMack commented on simple-chat/src/chatlist.html
> +<!DOCTYPE html>
Всё думаю про SPA, тут и так много что нужно сделать в этом ДЗ. А SPA вообще тема 6 лекции.