ДЗ 4
BrashMack/2024-2-VK-EDU-Frontend-G-Vostrikov pull request #4
Opened 2024-11-07 17:24 UTC by BrashMack

# Домашнее задание №4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

Что было сделано:
* Исправлены все замечания по ДЗ 3(сделал выбор аватара чата с устройства, переделал на SPA, теперь все чаты из списка работают, убрал alert-ы)
* Отключен зум 
* Анимация для только что отправленных сообщений
* Выделение пульсирующей анимацией для ещё не прочитанных пользователем сообщений
* Плавное появление модального меню создания нового чата
* Все остальные требования ДЗ были выполнены ранее

2024-11-10 10:20 UTC, Ivan-Bir requested changes
По формальным требованиям ок. Давай ускоряться
Из критичного: не работает сохранение нового чата. В localStorage запись имеется, но cам чат не может отрендериться. Если картинки не получается сохранять, то попробуй хранить их в base64.

Отмечу, что для некликабельных элементов можно использовать стиль cursor: not-allowed; Так хотя бы понятно, что это не сломано.
Также посмотри ещё раз на форму добавления нового чата. Элементы должны быть выровнены либо по левой стороне, либо по центру. Кнопку "галочка" лучше заменить с текстом, чтобы было нагляднее. Когда появляется ошибка в форме, то её не видно - не влезает целиком в инпут. Лучше выводить отдельным элементом на форме. И в целом не допускать много пустого незаполненного пространства в интерфейсе

2024-11-10 10:20 UTC, Ivan-Bir commented on simple-chat/src/components/chat/chat.js
> +    document.querySelector('#root').innerHTML = `
Есть более безопасные методы вставки контента в страницу https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

2024-11-10 10:20 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +            renderChat(currentView);
В следующем дз жду, что появится возможность открывать чат через параметры в url и делать навигацию через стрелочки браузера

2024-11-14 13:28 UTC, Ivan-Bir commented
Привет! Когда ожидаем правок?

2024-11-14 18:32 UTC, BrashMack commented
> Привет! Когда ожидаем правок?
Занимаюсь этим в данный момент.

2024-11-15 00:16 UTC, BrashMack commented
> По формальным требованиям ок. Давай ускоряться Из критичного: не работает сохранение нового чата. В localStorage запись имеется, но cам чат не может отрендериться. Если картинки не получается сохранять, то попробуй хранить их в base64.
> 
> Отмечу, что для некликабельных элементов можно использовать стиль cursor: not-allowed; Так хотя бы понятно, что это не сломано. Также посмотри ещё раз на форму добавления нового чата. Элементы должны быть выровнены либо по левой стороне, либо по центру. Кнопку "галочка" лучше заменить с текстом, чтобы было нагляднее. Когда появляется ошибка в форме, то её не видно - не влезает целиком в инпут. Лучше выводить отдельным элементом на форме. И в целом не допускать много пустого незаполненного пространства в интерфейсе

1) Может я не понял проблему, но у меня сохранение и рендер нового чата прекрасно работают, когда создавал pull request всё тоже работало.
2) Ошибка в форме влезает в инпут на любом устройстве. Даже на самом узком galaxy fold, со своего телефона тоже проверил, скрины прилагаются(делал до изменения модалки, но и после ничего не изменилось в этом плане.
![влезает](https://github.com/user-attachments/assets/4db5344d-4797-433c-9ef4-d77f5e5a4745)
![5310296255265629749](https://github.com/user-attachments/assets/dcd3bfff-46be-4914-b1af-78ef0f19daee)

2024-11-18 14:39 UTC, Ivan-Bir commented
Сейчас всё норм. Возможно не сбросил localStorage перед проверкой. А с ошибкой проблема в том, что инпут на моём экране занимал только небольшую часть формы слева

2024-11-18 14:39 UTC, Ivan-Bir approved these changes

2024-11-19 13:24 UTC, merged

2024-11-19 13:25 UTC, martinkomitsky commented
7