ДЗ 5
BrashMack/2024-2-VK-EDU-Frontend-G-Vostrikov pull request #5
Opened 2024-12-14 22:21 UTC by BrashMack

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

Что было сделано:
* Были выполнены все условия ДЗ. 
* Только я уже использую react-router, так как не заметил этого условия и ментор просил сделать навигацию по URL и стрелочкам браузера. Но есть и версия без react-router с использованием useState в этом [коммите](https://github.com/BrashMack/2024-2-VK-EDU-Frontend-G-Vostrikov/commit/b4b85c47d0df4f2d2ea443a6c2a7068835702e4d)

Ссылка на деплой: https://brashmack.github.io/2024-2-VK-EDU-Frontend-G-Vostrikov/
Деплой собрался и запустился нормально, конфиги поменял по инструкции, но при перезагрузке страницы в каком нибудь из чатов или при попытке перейти в чат по url, появляется ошибка 404(File not found), хотя в dev режиме у меня всё отлично работает. Так и не понял в чём проблема, может что-то с путями base(vite.config.js) или basename(App.jsx).

2024-12-15 19:37 UTC, Ivan-Bir requested changes
Привет. Давно тебя не было в уличных гонках!

По UI что успел посмотреть хорошо. Однако роутер всё-таки надо переделать на свой велосипедный, потому что в том в коммите не работала бы перезагрузка страницы через F5 (спойлер, она и не работает сейчас)

2024-12-15 19:37 UTC, Ivan-Bir commented on chat/README.md
> +- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
Описание надо поправить

2024-12-15 19:37 UTC, Ivan-Bir commented on chat/public/index.html
> +<html lang="ru">
Лишний файл

2024-12-15 19:37 UTC, Ivan-Bir commented on chat/src/components/ChatItem/ChatItem.jsx
> +  const noStatus = () => {
const noStatus = () => ['read', 'send', 'unread'].some((val) => val !== status[0]);

2024-12-15 19:37 UTC, Ivan-Bir commented on chat/src/components/MessageItem/MessageItem.module.scss
> +.img {
Не очень удачное имя для класса

2024-12-15 19:37 UTC, Ivan-Bir commented on chat/src/components/MessageItem/MessageItem.jsx
> +      {message.img ? (
Раз уж зачатки такой логики есть, то давай добьем до состояния, что можно отправлять картинки в сообщении

2024-12-15 19:37 UTC, Ivan-Bir commented on chat/index.html
> +<html lang="ru">
Лишний файл + убрать из репы всё, что не относится к версии приложения на react

2024-12-19 16:34 UTC, BrashMack commented on chat/index.html
> +<html lang="ru">
Я так понял один из файлов index.html лишний(забыл убрать). Убрал тот, что в папке public был.

2024-12-21 13:35 UTC, Ivan-Bir approved these changes

2024-12-22 09:08 UTC, merged

2024-12-22 09:08 UTC, martinkomitsky commented
7